### ISSUE TITLE
Don't send command if device is already in desired state

### ISSUE THREAD

**Issue by derjoerg** [kingsleyadam/local-abbfreeathome-hass#117]
Hi,

before adding a PR (which is pretty simple) I first wanted to have some opinions if e.g. I overlooked something.

So here is my usecase:
In HA I have several "DimmingActuators" and also "SwitchingActuators", which I defined as lights (switch-as-x). All these lights I have grouped together (a total of 28 lights + several other lights like shellys, hues, ...).
When I go to bed I simple switch off the "all-lights" entity to have all lights off, but even if e.g. only 2 lights are still on, the integration switches off all lights, also the once which are already off. So in my case it sends 28 REST-commands to F@H. This results in a "429" (too many requests) error and not all lights are switched off.
Here the error from HA:
```
2024-12-21 00:04:01.318 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140260859875904] Unexpected exception                                     
Traceback (most recent call last):                                                                                                                                             
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service                                                           
    response = await hass.services.async_call(                                                                                                                                 
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                
    ...<7 lines>...                                                                                                                                                            
    )                                                                                                                                                                          
    ^                                                                                                                                                                          
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call                                                                                                
    response_data = await coro                                                                                                                                                 
                    ^^^^^^^^^^                                                                                                                                                
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service                                                                                          
    return await target(service_call)                                                                                                                                          
           ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                          
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call                                                                            
    single_response = await _handle_entity_call(                                                                                                                               
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                               
        hass, entity, func, data, call.context                                                                                                                                 
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                 
    )                                                                                                                                                                          
    ^                                                                                                                                                                          
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call                                                                            
    result = await task                                                                                                                                                        
             ^^^^^^^^^^                                                                                                                                                        
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 639, in async_handle_light_off_service                                                        
    await light.async_turn_off(**filter_turn_off_params(light, params))                                                                                                        
  File "/usr/src/homeassistant/homeassistant/components/group/light.py", line 194, in async_turn_off                                                                           
    await self.hass.services.async_call(                                                                                                                                       
    ...<5 lines>...                                                                                                                                                            
    )                                                                                                                                                                          
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call                                                                                                
    response_data = await coro                                                                                                                                                 
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service                                                                                          
    return await target(service_call)                                                                                                                                          
           ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                          
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1032, in entity_service_call                                                                            
    raise result from None                                                                                                                                                     
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1628, in async_request_call                                                                              
    return await coro                                                                                                                                                          
           ^^^^^^^^^^                                                                                                                                                          
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call                                                                            
    result = await task                                                                                                                                                        
             ^^^^^^^^^^                                                                                                                                                        
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 639, in async_handle_light_off_service                                                       
    await light.async_turn_off(**filter_turn_off_params(light, params))                                                                                                        
  File "/usr/src/homeassistant/homeassistant/components/switch_as_x/entity.py", line 162, in async_turn_off                                                                    
    await self.hass.services.async_call(                                                                                                                                       
    ...<5 lines>...                                                                                                                                                            
    )                                                                                                                                                                          
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call                                                                                               
    response_data = await coro                                                                                                                                                 
                    ^^^^^^^^^^                                                                                                                                                 
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service                                                                                          
    return await target(service_call)                                                                                                                                          
           ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                          
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call                                                                            
    single_response = await _handle_entity_call(                                                                                                                               
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                               
        hass, entity, func, data, call.context                                                                                                                                 
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                 
    )                                                                                                                                                                          
    ^                                                                                                                                                                          
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call                                                                            
    result = await task                                                                                                                                                        
             ^^^^^^^^^^                                                                                                                                                        
  File "/config/custom_components/abbfreeathome/switch.py", line 88, in async_turn_off                                                                                         
    await self._switch.turn_off()                                                                                                                                              
  File "/usr/local/lib/python3.13/site-packages/abbfreeathome/devices/switch_actuator.py", line 77, in turn_off                                                                
    await self._set_switching_datapoint("0")                                                                                                                                   
  File "/usr/local/lib/python3.13/site-packages/abbfreeathome/devices/switch_actuator.py", line 120, in _set_switching_datapoint                                               
    return await self._api.set_datapoint(                                                                                                                                      
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                      
    ...<4 lines>...                                                                                                                                                            
    )                                                                                                                                                                          
    ^                                                                                                                                                                          
  File "/usr/local/lib/python3.13/site-packages/abbfreeathome/api.py", line 262, in _request                                                                                   
    raise InvalidApiResponseException(_response_status) from None                                                                                                              
abbfreeathome.exceptions.InvalidApiResponseException: Invalid api response, status code: 429
```

The solution would be (at least for SwitchingActuator and DimmingActuator), before sending the command, check if the device is already in the desired state and if so, don't send the command.

What do you think? Any drawbacks with this approach?

**Comment by derjoerg** [comment]
BTW: If OK, I would do the modification in the library (https://github.com/kingsleyadam/local-abbfreeathome) and not in the integration

**Comment by kingsleyadam** [comment]
I was afraid of this and I would have hoped Home Assistant would handle this better. As an integration maintainers, I'd assume Home Assistant would handle the "if light is off, don't turn off" logic and not something we have to worry about.

There must be a reason why Home Assistant is doing this, what if the light is in an incorrect state? e.g. the light sate is `Off` even though it's actually on?

What about the scenario where all lights are on and the integration needs to turn them off? Then we'd still get this 429 throttling response code.

Ideally we'd manage all of the devices with a single api call, but it doesn't look like the local api supports that, and it doesn't support that kind of traffic on the websocket either.

I _think_ the best approach for us, as integration maintainers, is to apply a retry with exponential backoff. Here's a pretty good write-up on how that works. https://medium.com/@suryasekhar/exponential-backoff-decorator-in-python-26ddf783aea0

**Comment by derjoerg** [comment]
This sounds very interessting. I will check the writing.

I also thought of an approach with implementing a kind of queue in the API-class for all commands, which should be executed against the API and only execute one command after the other e.g. every 10 ms (modifiable).

**Comment by derjoerg** [comment]
OK, I fully understand the delay aspect and if you already have good experience with "retry with exponential backoff" this should be the way to go.

I will close my issues and also the PR
