### ISSUE TITLE
Integration broken since 0.11.0

### ISSUE THREAD

**Issue by nrenner73** [kingsleyadam/local-abbfreeathome-hass#55]
Just updated to 0.11.0 and now all my devices are broken.

System log for a binary sensor says the following:
```
Logger: homeassistant.components.binary_sensor
Quelle: helpers/entity_platform.py:361
Integration: Binärsensor ([Dokumentation](https://www.home-assistant.io/integrations/binary_sensor), [Probleme](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
Erstmals aufgetreten: 15:03:05 (1 Vorkommnisse)
Zuletzt protokolliert: 15:03:05

Error while setting up abbfreeathome_ci platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/abbfreeathome_ci/binary_sensor.py", line 84, in async_setup_entry
    for device in free_at_home.get_device_by_class(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FreeAtHome' object has no attribute 'get_device_by_class'. Did you mean: 'get_devices_by_class'?
```

The same applies for all other components like `button`, `event`, `light` and so on. Did I make a mistake or is there a typo somewhere in `get_device_by_class` and`get_devices_by_class`?

**Comment by kingsleyadam** [comment]
Sorry about that, I just cut a new release 0.11.1 to fix this.

**Comment by nrenner73** [comment]
Working again with 0.11.1

Solved lightning fast! 

Thanks!
