### ISSUE TITLE
Add BlindActuator as cover entity

### ISSUE THREAD

**Issue by derjoerg** [kingsleyadam/local-abbfreeathome-hass#72]

**Comment by kingsleyadam** [comment]
Implemented in the python package with https://github.com/kingsleyadam/local-abbfreeathome/pull/79

**Comment by derjoerg** [comment]
I have no "Attic Window" and also no covers with tilt-possibility in my setup, so I'm not able to finally test it.

**Comment by nrenner73** [comment]
> I have no "Attic Window" and also no covers with tilt-possibility in my setup, so I'm not able to finally test it.

I can test these. Will try in the evening.

**Comment by nrenner73** [comment]
I think I need a bit of help with this. I pulled init.py and cover.py from PR#89 but now I get an error at startup:

```
Logger: homeassistant.config_entries
Quelle: config_entries.py:635
Erstmals aufgetreten: 16:42:17 (1 Vorkommnisse)
Zuletzt protokolliert: 16:42:17

Error setting up entry Free@Home-SysAP (ABB7F62FB3A6) for abbfreeathome_ci
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/abbfreeathome_ci/__init__.py", line 88, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2242, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1181, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1181, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1181, in async_get_platforms
    import_future.result()
  [Previous line repeated 8 more times]
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1169, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1094, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1268, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1300, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/abbfreeathome_ci/cover.py", line 5, in <module>
    from abbfreeathome.devices.cover_actuator import (
ImportError: cannot import name 'CoverActuatorState' from 'abbfreeathome.devices.cover_actuator' (/usr/local/lib/python3.12/site-packages/abbfreeathome/devices/cover_actuator.py)
```

I believe I need cover_actuator.py from the Python package but I don´t know where to put it.

**Comment by derjoerg** [comment]
which version is in the requirements-key of your manifest.json?

**Comment by nrenner73** [comment]
```
{
  "domain": "abbfreeathome_ci",
  "name": "ABB-free@home",
  "codeowners": ["@kingsleyadam"],
  "config_flow": true,
  "dependencies": [],
  "documentation": "https://github.com/kingsleyadam/local-abbfreeathome-hass",
  "homekit": {},
  "iot_class": "local_push",
  "requirements": ["local-abbfreeathome==1.14.1"],
  "ssdp": [],
  "version": "0.13.0",
  "zeroconf": [
    {
      "type": "_http._tcp.local.",
      "name": "free@home*"
    }
  ]
}
```

**Comment by derjoerg** [comment]
Modify it to have "local-abbfreeathome==1.15.1"
Put the modified init.py and cover.py in place and restart HA

**Comment by nrenner73** [comment]
Thanks!
That and the addition of lock.py and select.py brought it back to life.

I already can see the actuators of my blinds.
Let me play a bit with it ...

**Comment by nrenner73** [comment]
Attic Window works. I already love the forced_open and forced_closed, as this makes closing the window and locking the switch during a rain alarm quite easy!

Covers:  
- with setup as a roller shutter (german: 'Rolladen') up and down by short press works. Forced_open is also great in situations with strong winds! This all works as it should!
- with setup sunblind/shutter. Well I´m not sure about the correct translation, in german it´s a 'Jalousie' up and down by short press works, but I do not see a possibility to tilt the slats.
![2024-11-16](https://github.com/user-attachments/assets/052969d8-653a-40e9-b319-755b9917d376)

- I cannot test my sunshade/awning/canvas blind (german: 'Sonnensegel') as this is packed for winter but the buttons are there
![2024-11-16 (1)](https://github.com/user-attachments/assets/0891a2d7-d0c2-4504-8400-1142e63d38dd)

**Comment by derjoerg** [comment]
> * with setup sunblind/shutter. Well I´m not sure about the correct translation, in german it´s a 'Jalousie' up and down by short press works, but I do not see a possibility to tilt the slats.

Have you set them up in F@H as "Jalousie"?

**Comment by nrenner73** [comment]
Des

**Comment by derjoerg** [comment]
> Yes

Can you provide the config of that device?

**Comment by nrenner73** [comment]
```
"ABB7F6318718": {
        "deviceReboots": "30",
        "floor": "02",
        "room": "06",
        "interface": "RF",
        "deviceId": "2039",
        "displayName": "Arbeitszimmer Jalousie",
        "unresponsive": false,
        "unresponsiveCounter": 0,
        "defect": false,
        "channels": {
          "ch0000": {
            "displayName": "Arbeitszimmer Jalousie",
            "floor": "02",
            "function": "FID_BLIND_SENSOR",
            "functionID": "3",
            "inputs": {
              "idp0001": {
                "pairing": "AL_NIGHT",
                "pairingID": 18,
                "value": "1"
              },
              "idp0002": {
                "pairing": "AL_INFO_ERROR",
                "pairingID": 273,
                "value": "0"
              },
              "idp0005": {
                "pairing": "AL_SYSAP_INFO_ERROR",
                "pairingID": 278,
                "value": ""
              }
            },
            "outputs": {
              "odp0002": {
                "pairing": "AL_MOVE_UP_DOWN",
                "pairingID": 32,
                "value": "0"
              },
              "odp0003": {
                "pairing": "AL_STOP_STEP_UP_DOWN",
                "pairingID": 33,
                "value": "0"
              },
              "odp0006": {
                "pairing": "AL_SCENE_CONTROL",
                "pairingID": 4,
                "value": ""
              }
            },
            "parameterNames": {
              "PID_LED_NIGHT_BRIGHTNESS (par0002)": "20",
              "PID_LED_DAY_BRIGHTNESS (par0001)": "50",
              "PID_LED_OPERATION_MODE (par0007)": "1"
            },
            "parameters": {
              "par0002": "20",
              "par0001": "50",
              "par0007": "1"
            },
            "room": "06"
          },
          "ch0009": {
            "displayName": "Arbeitszimmer Jalousie ",
            "floor": "02",
            "function": "FID_SHUTTER_ACTUATOR",
            "functionID": "9",
            "inputs": {
              "idp0000": {
                "pairing": "AL_MOVE_UP_DOWN",
                "pairingID": 32,
                "value": "1"
              },
              "idp0001": {
                "pairing": "AL_STOP_STEP_UP_DOWN",
                "pairingID": 33,
                "value": "1"
              },
              "idp0002": {
                "pairing": "AL_SET_ABSOLUTE_POSITION_BLINDS_PERCENTAGE",
                "pairingID": 35,
                "value": ""
              },
              "idp0003": {
                "pairing": "AL_SET_ABSOLUTE_POSITION_SLATS_PERCENTAGE",
                "pairingID": 36,
                "value": ""
              },
              "idp0004": {
                "pairing": "AL_FORCED_UP_DOWN",
                "pairingID": 40,
                "value": "0"
              },
              "idp0005": {
                "pairing": "AL_WIND_ALARM",
                "pairingID": 37,
                "value": ""
              },
              "idp0006": {
                "pairing": "AL_RAIN_ALARM",
                "pairingID": 39,
                "value": ""
              },
              "idp0007": {
                "pairing": "AL_FROST_ALARM",
                "pairingID": 38,
                "value": ""
              },
              "idp0008": {
                "pairing": "AL_SCENE_CONTROL",
                "pairingID": 4,
                "value": "2"
              },
              "idp0009": {
                "pairing": "AL_WINDOW_DOOR",
                "pairingID": 53,
                "value": ""
              }
            },
            "outputs": {
              "odp0000": {
                "pairing": "AL_INFO_MOVE_UP_DOWN",
                "pairingID": 288,
                "value": "1"
              },
              "odp0001": {
                "pairing": "AL_CURRENT_ABSOLUTE_POSITION_BLINDS_PERCENTAGE",
                "pairingID": 289,
                "value": "100"
              },
              "odp0002": {
                "pairing": "AL_CURRENT_ABSOLUTE_POSITION_SLATS_PERCENTAGE",
                "pairingID": 290,
                "value": "100"
              },
              "odp0003": {
                "pairing": "AL_INFO_ERROR",
                "pairingID": 273,
                "value": "0"
              },
              "odp0004": {
                "pairing": "AL_INFO_FORCE",
                "pairingID": 257,
                "value": "0"
              }
            },
            "parameterNames": {
              "PID_TOTAL_BLINDS_MOVEMENT_TIME (par0008)": "22",
              "PID_TOTAL_BLINDS_MOVEMENT_TIME_DOWN (par0035)": "21",
              "PID_TOTAL_SLATS_MOVEMENT_TIME (par000a)": "1400",
              "PID_TOTAL_BLINDS_MOVEMENT_TIME_CALIBRATED (par0009)": "2",
              "PID_TOTAL_BLINDS_MOVEMENT_TIME_CALIBRATED_DOWN (par0036)": "2",
              "PID_TOTAL_SLATS_MOVEMENT_TIME_CALIBRATED (par000b)": "2",
              "PID_BEHAVIOUR_ON_MALFUNCTION (par0014)": "1",
              "PID_ENGINE_SWITCH_ON_DELAY_TIME (par0037)": "50",
              "PID_REFERENCE_DRIVE_BEFORE_POSITIONING (par0054)": "1",
              "PID_BEHAVIOUR_DISABLE_FORCE (par005c)": "1",
              "PID_HANDLE_WIND_ALARM (par0058)": "2",
              "PID_HANDLE_RAIN_ALARM (par0059)": "2",
              "PID_HANDLE_FROST_ALARM (par005a)": "3",
              "PID_HANDLE_WINDOW_ALARM (par005b)": "2"
            },
            "parameters": {
              "par0008": "22",
              "par0035": "21",
              "par000a": "1400",
              "par0009": "2",
              "par0036": "2",
              "par000b": "2",
              "par0014": "1",
              "par0037": "50",
              "par0054": "1",
              "par005c": "1",
              "par0058": "2",
              "par0059": "2",
              "par005a": "3",
              "par005b": "2"
            },
            "room": "06",
            "selectedIcon": "03"
          },
          "ch000a": {
            "displayName": "Arbeitszimmer Jalousie",
            "floor": "02",
            "function": "FID_BLIND_SENSOR",
            "functionID": "3",
            "inputs": {},
            "outputs": {
              "odp0002": {
                "pairing": "AL_MOVE_UP_DOWN",
                "pairingID": 32,
                "value": "0"
              },
              "odp0003": {
                "pairing": "AL_STOP_STEP_UP_DOWN",
                "pairingID": 33,
                "value": "0"
              }
            },
            "parameterNames": {
              "PID_BI_CONTACT_TYPE (par0010)": "1"
            },
            "parameters": {
              "par0010": "1"
            },
            "room": "06"
          }
        },
        "parameters": {
          "par00ed": "1",
          "par00eb": "1"
        },
        "parameterNames": {
          "PID_CHANNEL_SELECTOR_1_GANG (par00ed)": "1",
          "PID_CHANNEL_SELECTOR_AUX_INPUT_SHUTTER (par00eb)": "1"
        }
      },
```

**Comment by nrenner73** [comment]
One thing I noticed with my 'Sonnensegel'. It is closed at the moment because it is wrapped up in a cover for winter. But the buttons only offer to close it (see my screenshot above).
I´m not sure if this is because of my configuration. In my case, pushing the bottom of the switch unfolds it. 
Also I would assume the same setting for a 'Markise'.

**Comment by kingsleyadam** [comment]
To me the naming looks correct. You've named the blinds `Arbeitszimmer Jalousie ` in Free@Home so that's what's coming through in Home Assistant. I can also tell the Device Name and Channel Name are actually different because of the extra space added to the channel name `Arbeitszimmer Jalousie` vs `Arbeitszimmer Jalousie `.

**Comment by derjoerg** [comment]
Your configuration looks exactly as I expected. But - for whatever reason - the integration seems to register your "Jalousie" as "Rollladen".
I'm now just asking some general questions (please don't feel offended:
- Can you control the slats in F@H?
- Have you tried to completely delete your SysAP in HA, restart HA and re-add the SysAP?

**Comment by kingsleyadam** [comment]
@nrenner73 , I think it'd be most helpful if you could past the configuration for all of your "cover" type of devices.

**Comment by derjoerg** [comment]
I just did a test and configured one of my "Rollladen" as a "Jalousie" in F@H (even that I have no slats). And when I add the integration completely new in HA it shows up correctly and the "slats" can be controlled.
![jalousie](https://github.com/user-attachments/assets/ebbf433b-b9f5-45e8-b347-0cce7a6852c3)

**Comment by nrenner73** [comment]
Maybe I was just too dumb to get it rigth. I believe I never clicked on the name of the blind to get the popup window. Here we go, I can adjust the tilt just fine:


![2024-11-16 (2)](https://github.com/user-attachments/assets/72f0dc8a-5fed-4e26-b127-c49837d92950)

Sorry for the confusion!

**Comment by derjoerg** [comment]
> Sorry for the confusion!

All good. Nice that it is working for you

**Comment by nrenner73** [comment]
Question: I got lost following your conversation about the new Switch/Blind/... Events.
What use can I make of these events?

**Comment by derjoerg** [comment]
> Question: I got lost following your conversation about the new Switch/Blind/... Events. What use can I make of these events?

I don't use them, but the following use-case comes into my mind:
- You have a physical F@H-Switch-Sensor, -Blind-Sensor, -Dimming-Sensor and have not paired it with a device in F@H
- In HA you can now link this - through an automation - to a e.g. Shelly-Device, which controls a light

**Comment by kingsleyadam** [comment]
> One thing I noticed with my 'Sonnensegel'. It is closed at the moment because it is wrapped up in a cover for winter. But the buttons only offer to close it (see my screenshot above).
> 
> I´m not sure if this is because of my configuration. In my case, pushing the bottom of the switch unfolds it. 
> 
> Also I would assume the same setting for a 'Markise'.

Are we ok on this one?

**Comment by derjoerg** [comment]
> > One thing I noticed with my 'Sonnensegel'. It is closed at the moment because it is wrapped up in a cover for winter. But the buttons only offer to close it (see my screenshot above).
> > I´m not sure if this is because of my configuration. In my case, pushing the bottom of the switch unfolds it.
> > Also I would assume the same setting for a 'Markise'.
> 
> Are we ok on this one?

I can only state, that I have such a behaviour sometimes also with my covers. I just click on "close", even that it is already closed and everything is fine and controlable.

**Comment by nrenner73** [comment]
> > > One thing I noticed with my 'Sonnensegel'. It is closed at the moment because it is wrapped up in a cover for winter. But the buttons only offer to close it (see my screenshot above).
> > > I´m not sure if this is because of my configuration. In my case, pushing the bottom of the switch unfolds it.
> > > Also I would assume the same setting for a 'Markise'.
> > 
> > 
> > Are we ok on this one?
> 
> I can only state, that I have such a behaviour sometimes also with my covers. I just click on "close", even that it is already closed and everything is fine and controlable.

OK, this test will have to wait until spring. I cannot link the sensor to the actuator now and risk a major havoc with the packed up sunshade.

**Comment by kingsleyadam** [comment]
> I can only state, that I have such a behaviour sometimes also with my covers. I just click on "close", even that it is already closed and everything is fine and controlable.

Hmm, that tells me the initial state isn't correct and only gets corrected after a post from the websocket? Strange.

Let me know if we're good on this one and I can merge it in.

**Comment by derjoerg** [comment]
> OK, this test will have to wait until spring. I cannot link the sensor to the actuator now and risk a major havoc with the packed up sunshade.

Just to be sure, can you also paste the config of your "Sonnensegel"?

**Comment by nrenner73** [comment]
Here it is:

```
  "ABB7F63186FD": {
        "deviceReboots": "22",
        "floor": "02",
        "room": "02",
        "interface": "RF",
        "deviceId": "2039",
        "displayName": "Terrasse Sonnensegel",
        "unresponsive": false,
        "unresponsiveCounter": 0,
        "defect": false,
        "channels": {
          "ch0000": {
            "displayName": "Terrasse Sonnensegel",
            "floor": "02",
            "function": "FID_BLIND_SENSOR",
            "functionID": "3",
            "inputs": {
              "idp0001": {
                "pairing": "AL_NIGHT",
                "pairingID": 18,
                "value": "1"
              },
              "idp0002": {
                "pairing": "AL_INFO_ERROR",
                "pairingID": 273,
                "value": "0"
              },
              "idp0005": {
                "pairing": "AL_SYSAP_INFO_ERROR",
                "pairingID": 278,
                "value": ""
              }
            },
            "outputs": {
              "odp0002": {
                "pairing": "AL_MOVE_UP_DOWN",
                "pairingID": 32,
                "value": "0"
              },
              "odp0003": {
                "pairing": "AL_STOP_STEP_UP_DOWN",
                "pairingID": 33,
                "value": "0"
              },
              "odp0006": {
                "pairing": "AL_SCENE_CONTROL",
                "pairingID": 4,
                "value": ""
              }
            },
            "parameterNames": {
              "PID_LED_NIGHT_BRIGHTNESS (par0002)": "20",
              "PID_LED_DAY_BRIGHTNESS (par0001)": "50",
              "PID_LED_OPERATION_MODE (par0007)": "1"
            },
            "parameters": {
              "par0002": "20",
              "par0001": "50",
              "par0007": "1"
            },
            "room": "02"
          },
          "ch0009": {
            "displayName": "Terrasse Sonnensegel",
            "floor": "02",
            "function": "FID_AWNING_ACTUATOR",
            "functionID": "63",
            "inputs": {
              "idp0000": {
                "pairing": "AL_MOVE_UP_DOWN",
                "pairingID": 32,
                "value": "0"
              },
              "idp0001": {
                "pairing": "AL_STOP_STEP_UP_DOWN",
                "pairingID": 33,
                "value": "1"
              },
              "idp0002": {
                "pairing": "AL_SET_ABSOLUTE_POSITION_BLINDS_PERCENTAGE",
                "pairingID": 35,
                "value": ""
              },
              "idp0004": {
                "pairing": "AL_FORCED_UP_DOWN",
                "pairingID": 40,
                "value": ""
              },
              "idp0005": {
                "pairing": "AL_WIND_ALARM",
                "pairingID": 37,
                "value": ""
              },
              "idp0006": {
                "pairing": "AL_RAIN_ALARM",
                "pairingID": 39,
                "value": ""
              },
              "idp0007": {
                "pairing": "AL_FROST_ALARM",
                "pairingID": 38,
                "value": ""
              },
              "idp0008": {
                "pairing": "AL_SCENE_CONTROL",
                "pairingID": 4,
                "value": ""
              }
            },
            "outputs": {
              "odp0000": {
                "pairing": "AL_INFO_MOVE_UP_DOWN",
                "pairingID": 288,
                "value": "0"
              },
              "odp0001": {
                "pairing": "AL_CURRENT_ABSOLUTE_POSITION_BLINDS_PERCENTAGE",
                "pairingID": 289,
                "value": "0"
              },
              "odp0003": {
                "pairing": "AL_INFO_ERROR",
                "pairingID": 273,
                "value": "0"
              },
              "odp0004": {
                "pairing": "AL_INFO_FORCE",
                "pairingID": 257,
                "value": "0"
              }
            },
            "parameterNames": {
              "PID_TOTAL_BLINDS_MOVEMENT_TIME (par0008)": "83",
              "PID_TOTAL_BLINDS_MOVEMENT_TIME_DOWN (par0035)": "74",
              "PID_TOTAL_SLATS_MOVEMENT_TIME (par000a)": "0",
              "PID_TOTAL_BLINDS_MOVEMENT_TIME_CALIBRATED (par0009)": "2",
              "PID_TOTAL_BLINDS_MOVEMENT_TIME_CALIBRATED_DOWN (par0036)": "2",
              "PID_TOTAL_SLATS_MOVEMENT_TIME_CALIBRATED (par000b)": "2",
              "PID_BEHAVIOUR_ON_MALFUNCTION (par0014)": "1",
              "PID_ENGINE_SWITCH_ON_DELAY_TIME (par0037)": "0",
              "PID_REFERENCE_DRIVE_BEFORE_POSITIONING (par0054)": "1",
              "PID_BEHAVIOUR_DISABLE_FORCE (par005c)": "1",
              "PID_HANDLE_WIND_ALARM (par0058)": "2",
              "PID_HANDLE_RAIN_ALARM (par0059)": "2",
              "PID_HANDLE_FROST_ALARM (par005a)": "2"
            },
            "parameters": {
              "par0008": "83",
              "par0035": "74",
              "par000a": "0",
              "par0009": "2",
              "par0036": "2",
              "par000b": "2",
              "par0014": "1",
              "par0037": "0",
              "par0054": "1",
              "par005c": "1",
              "par0058": "2",
              "par0059": "2",
              "par005a": "2"
            },
            "room": "FB",
            "selectedIcon": "106"
          },
          "ch000a": {
            "displayName": "Terrasse Sonnensegel",
            "floor": "02",
            "function": "FID_BLIND_SENSOR",
            "functionID": "3",
            "inputs": {},
            "outputs": {
              "odp0002": {
                "pairing": "AL_MOVE_UP_DOWN",
                "pairingID": 32,
                "value": "0"
              },
              "odp0003": {
                "pairing": "AL_STOP_STEP_UP_DOWN",
                "pairingID": 33,
                "value": "0"
              }
            },
            "parameterNames": {
              "PID_BI_CONTACT_TYPE (par0010)": "1"
            },
            "parameters": {
              "par0010": "1"
            },
            "room": "02"
          }
        },
        "parameters": {
          "par00ed": "1",
          "par00eb": "1"
        },
        "parameterNames": {
          "PID_CHANNEL_SELECTOR_1_GANG (par00ed)": "1",
          "PID_CHANNEL_SELECTOR_AUX_INPUT_SHUTTER (par00eb)": "1"
        }
      },
```

**Comment by nrenner73** [comment]
I just saw that the icon behaviour of the sunshade is exactly the same in the free@home integration by jheling.
So maybe it´s my setup.
I´m good on that topic.

**Comment by derjoerg** [comment]
> 
> Let me know if we're good on this one and I can merge it in.

You can merge it :smiley:
